JanMate/happy_bank_infra

README.md
It adds commit message section to README.md.
Closes #3
=> minor: Add commit message format

README.md
It adds workflow section to README.md.
Closes #7
=> minor: Add workflow guide

clone_update_repo.sh
It adds skeleton of git exam in clone_update_repo.sh.
Closes nothing
=> minor: Add git exam script

README.md
It adds section how to prevent merging of unfinished work.
Closes nothing
=> minor: Add WIP flag section to README.md

run_docker.sh
It adds skeleton of git exam in run_docker.sh.
Closes nothing
=> minor: Add docker exam script

.github/workflows/bash_scripts.yml
It fixes setup for clone_update_repo.sh script on CI pipeline.
Closes nothing
=> minor: Fix shell testing on CI pipeline

clone_update_repo.sh
Added new instructions to clone_update_repo file
Closes #9
=> Minor - Updated clone_update_repo file

run_docker.sh
=> Minor: Updated run_docker file

clone_update_repo.sh
Fixed "useless cat" error by shellcheck
Closes #22
=> Minor: Implemented small fix

kubernetes/core-pod.yml, kubernetes/core-svc.yml
Created first version of core app pod
Closes #5
=> Minor: Updated core-pod.yml

kubernetes/core-pod.yml
Implemented readiness and liveness probes
Closes #37
=> Minor: Added pod health checks

kubernetes/core-pod.yml, kubernetes/core-svc.yml
Changed core-app pod docker image
Closes #50
=> Minor: Updated docker image

kubernetes/core-job.yml
**IMPORTANT NOTICE:** Merge after #56 is merged due to branch dependency!!!
Implemented k8s job to verify if app is up and running
Closes #35
=> Minor: Added k8s job

.github/workflows/ci.yml
Adds kubectl dry-run and server-dry-run steps into test job.
Closes nothing
=> ci: Add kubeval and kube-score verification

kubernetes/core-secret.yml
Created core-secret.yml for storing token value
Closes #45
=> Minor: Created core-secret.yml

.github/workflows/ci.yml, .sv4git.yml
Sets sv4git stages for semantic versioning.
Closes nothing
=> ci: Switch from semantic-release to sv4git

.github/workflows/ci.yml, .sv4git.yml
Sets semantic version pattern for sv4git in its config file.
Closes nothing
=> ci: Change tag pattern for sv4git

.github/workflows/ci.yml, kubernetes/ingress.yml
It creates core-app ingress
Closes #48
=> feat: created core-app ingress

.github/workflows/ci.yml, .sv4git.yml
Changes tag pattern starting with 'v'.
Closes nothing
=> ci: Change tag pattern

.github/workflows/ci.yml
Changes sv4git install stage.
Closes nothing
=> ci: Change sv4git install

.github/workflows/ci.yml
Sets checkout fetch depth.
Closes nothing
=> ci: Set checkout fetch depth

kubernetes/redis-config.yml
Creates redis configmap with host and port values
Closes #53
=> feat: create redis configmap

kubernetes/core-pod.yml, kubernetes/storage.yml
Created pv, pvc and set mounting to core app pod
=> feat: created pv for core app

kubernetes/core-deployment.yml
creates k8s deployment for core application
Closes #51
=> feat: create deployment

kubernetes/core-deployment.yml
it adds mounting of k8s secret and configmap into pod
Closes #46
=> feat: set configmap/secret mounting

.github/workflows/ci.yml, helm/Chart.yaml, helm/templates/config.yml, helm/templates/deployment.yml, helm/templates/ingress.yml, helm/templates/job.yml, helm/templates/secret.yml, helm/templates/storage.yml, helm/templates/svc.yml, helm/values.yaml
it creates Chart.yaml and values.yaml files
Closes #52
=> feat: create Chart and values files

helm/templates/deployment.yml, helm/values.yaml
it adds secret and redis configmap mounting to helm template
Closes nothing
=> feat: add secret and configmap mounting to helm template
